### ISSUE TITLE
cup, cup_eのhtmlファイルで、titleを「PWS****」 -> 「PWSCUP****」に変更する

### ISSUE THREAD

**Issue by gghatano** [pwscup/pwssite#227]
cup用のヘッダを用意して、htmlを作成する時にそれを参照する

**Comment by gghatano** [comment]
https://github.com/pwscup/pwssite/commit/58e41b6e5d93232d23fe5ffee9086e8f41dc1ae1
if文を追加して対応しました

https://github.com/pwscup/pwssite/tree/gh-pages/2022/template
cupファイル用のヘッダを別に作っています

**Comment by gghatano** [comment]
@nackamura  お時間ある時に確認お願いします cup用ヘッダは反映済みです

**Comment by nackamura** [comment]
ありがとうございます！
確認いたしました。CupページについてはこれでOKと思います！
cup以外のページにも対応できないかちょっと考えてみますね。

**Comment by nackamura** [comment]
@gghatano 
[feature/title_element](https://github.com/pwscup/pwssite/tree/feature/title_element) ブランチにて、
mdファイルの最初に登場する "# ..." を読み取って title タグ化するバージョンを作ってみました。
変更箇所のご確認は、 gh-pages とdiff していただけたらと思います。
イケてるかわかりませんが、動作ご確認いただけますと幸いです。

**Comment by gghatano** [comment]
すごい

**Comment by gghatano** [comment]
ありがとうございました

**Comment by nackamura** [comment]
こちらこそ、ご確認ありがとうございました！
